version: 2 # Specify the version of the Dependabot configuration

updates:
  - package-ecosystem: "maven" # Define the package ecosystem to be updated (Maven)
    directory: "/" # Specify the directory containing the dependencies
    schedule:
      interval: "weekly" # Set the update schedule to weekly

  - package-ecosystem: "github-actions" # Define the package ecosystem to be updated (GitHub Actions)
    directory: "/.github/workflows" # Specify the directory containing the GitHub Actions workflows
    schedule:
      interval: "weekly" # Set the update schedule to weekly
