image: gitpod/workspace-java-21

tasks:
  - name: Build
    init: mvn install
    command: echo "Build complete with Java 21"

# Optionally, expose ports or set up VS Code extensions here
# ports:
#   - port: 8080
#     onOpen: open-preview
