name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn install

      - name: Upload war file
        uses: actions/upload-artifact@v3
        with:
          name: war-file
          path: target/*.war

  upload-release-asset:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Upload war file to GitHub package
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/*.war
          asset_name: sample.war
          asset_content_type: application/zip
