name: Build and Deploy

# Define the events that trigger the workflow
on:
  push: # Trigger on push events to the main branch
    branches:
      - main
  pull_request: # Trigger on pull request events to the main branch
    branches:
      - main
  release: # Trigger on release creation
    types: [created]
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  contents: write # Grant write permission to the contents

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # Check out the repository code

      - name: Set up Java 17
        uses: actions/setup-java@v4 # Set up Java 17 environment
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn install # Build the project using Maven

      - name: List target directory contents
        run: ls -la target # List the contents of the target directory

      - name: Upload war file
        uses: actions/upload-artifact@v4 # Upload the built WAR file as an artifact
        with:
          name: war-file
          path: target/*.war

  create-release:
    needs: build # This job depends on the build and upload-release-asset jobs
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    if: github.event.release.tag_name != '' # Only run this job if the release tag name is not null
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # Check out the repository code

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build war file
        run: mvn install # Build the project to generate the WAR file

      - name: Verify build success
        run: |
          if [ ! -f target/*.war ]; then
            echo "WAR file not found in target directory"
            exit 1
          fi

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions' # Set Git user name
          git config --global user.email 'github-actions@github.com' # Set Git user email

      - name: Get version
        id: version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT # Get the project version

      - name: Update project version
        run: mvn versions:set -DnewVersion="$(date +'%Y.%m.%d-%H%M%S')" # Update the project version to the current date and time

      - name: Commit updated pom.xml
        run: |
          git add pom.xml # Add the updated pom.xml to Git
          git commit -m "Update project version to $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" # Commit the changes

      - name: Create release
        uses: softprops/action-gh-release@v2 # Create a new GitHub release
        with:
          tag_name: ${{ format('v{0}', steps.version.outputs.version) }} # Set the tag name for the release
          name: Release ${{ format('v{0}', steps.version.outputs.version) }} # Set the name for the release
          draft: false # Mark the release as not a draft
          prerelease: false # Mark the release as not a pre-release
          files: target/*.war # Attach the WAR file to the release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Pull latest changes
        run: git pull --rebase origin main

      - name: Push changes
        run: git push origin HEAD:main

      - name: Push changes
        run: git push origin HEAD:main # Push the changes to the main branch

  upload-release-asset:
    needs: [build, create-release] # This job depends on the build job
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    if: github.event.release.tag_name != '' # Only run this job if the release tag name is not null
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # Check out the repository code

      - name: Download war file
        uses: actions/download-artifact@v4 # Download the WAR file artifact
        with:
          name: war-file
          path: target

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Upload war file to GitHub release
        run: gh release upload ${{ github.event.release.tag_name }} target/*.war --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Verify upload
        run: gh release view ${{ github.event.release.tag_name }} --json assets -q '.assets[].name'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
