name: Trigger Dependabot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Trigger Dependabot
        run: |
          gh workflow run .github/dependabot.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
